### ISSUE TITLE
Uses an Outdated Dependency to Work and Prevents You From Logging On Vanilla 1.15

### ISSUE THREAD

**Issue by ghost** [LambdAurora/AuroraKeystrokes#2] opened 2019-12-22 17:29 UTC
Gives an error when you try to log in to vanilla servers using the dependency.

**Comment by LambdAurora** [comment] 2019-12-22 18:11
Hello, can you give me more details? I would need info about:
 - Fabric version used
 - List of the mods installed
 - An IP if possible of a server which the issue happen
 - The error

**Comment by ghost** [comment] 2019-12-23 15:53
Fabric Version Used: Latest
List of Mods Used: Aurora Keystokes, Cotton Client Commands And Fabric Api
IP: 51.91.44.128
Error: Java.Lang.NullPointerException

**Comment by ghost** [comment] 2019-12-23 16:01
And now it suddenly worked

**Comment by LambdAurora** [comment] 2019-12-23 17:28
I'm not able to reproduce the issue, might be a server-error.

And it seems everything is working again as you said so I will close the issue, if it happens again please re-open the issue and re-give all the needed details and the error message and stacktrace.

**Closed as completed by LambdAurora** 2019-12-23 17:28 UTC
Labels: bug
